apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flighttickets.flights.example.com
spec:
  group: flights.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                passengerName:
                  type: string
                flightNumber:
                  type: string
                departureAirport:
                  type: string
                arrivalAirport:
                  type: string
                departureTime:
                  type: string
                arrivalTime:
                  type: string
  scope: Namespaced
  names:
    plural: flighttickets
    singular: flightticket
    kind: FlightTicket
    shortNames:
    - ft
