apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd

  volumes:
    - name: claim-log-1
      persistentVolumeClaim:
        claimName: myclaim

