apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 80
      livenessProbe:
        httpGet:
          path: /live
          port: 8080
        periodSeconds: 1
        initialDelaySeconds: 80

