apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageclasses-admin

rules:
  - apiGroups: [""]
    resources: ["storageclasses"]
    verbs: ["list", "get", "create", "update", "delete"]
  
  