apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
  nodeSelector:
    size: Large # this is a label set on the node it slef, you have to set it prior to creating the pod, kubectl label nodes "nodeame" label-key=label-value

  affinity:
    nodeAffinity:
      # preferredDuringSchedulingIgnoredDuringExecution:
        # - preference:
            
          # weight: 
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - "Large"
                  - "Medium"